<../../../mkconfig

TARG=\

TESTS=\
	queue.dis\
	readn-chan.dis\
	readn-fd.dis\
	reads-chan.dis\
	reads-fd.dis\
	smoke.dis\
	write-chan.dis\
	write-fd.dis\
	write-epipe.dis\

SYSMODULES=\
	sys.m\
	draw.m\
	arg.m\

MODULES=\
	../../../module/iobuf.m\
	./share.m\

<../../../../tap/mktest
LIMBOFLAGS=$LIMBOFLAGS -I$INFERNO_HOME
