<../../../mkconfig

TARG=\

TESTS=\
	smoke.dis\
	reads-fd.dis\

SYSMODULES=\
	sys.m\
	draw.m\
	arg.m\

MODULES=\
	../../../module/iobuf.m\

<../../../../tap/mktest
LIMBOFLAGS=$LIMBOFLAGS -I$INFERNO_HOME
