PKGDIR=../../..
<$PKGDIR/mkconfig


TESTS=\
	queue.dis\
	readn-chan.dis\
	readn-fd.dis\
	reads-chan.dis\
	reads-fd.dis\
	smoke.dis\
	write-chan.dis\
	write-fd.dis\
	write-file2chan.dis\
	write-epipe.dis\

TESTTARG=\

SYSMODULES=\
	sys.m\
	draw.m\

OPTMODULES=\
	opt/powerman/tap/module/t.m\
	opt/powerman/tap/module/tap.m\

MODULES=\
	$PKGDIR/module/iobuf.m\
	$PKGDIR/appl/lib/t/share.m\

<$MKFILES/mktest
